available::available("yesSIR")
usethis::create_package("C:/SSD/Stage AO/yesSIR")
usethis::use_build_ignore("dev_history.R")
usethis::use_package("flextable")
usethis::use_package("SensoMineR")
usethis::use_package("FactoMineR")
usethis::use_package("openxlsx")
usethis::use_package("officer")
usethis::use_tidy_description()
attachment::att_to_description()
usethis::use_r("yes_MCA")
